### PR TITLE
tested list format of yaqd status for REPL and related scripting

### LINKED ISSUE #3: backfill releases

### PR DESCRIPTION
**Pull request by kameyer226**
Some syntax/naming could be adjusted but this is what I had in mind.   

Closes #3

### CODE REVIEW

**Comment by kameyer226** [comment]
oops forgot to mention it is list instead of dict now

**Comment by ksunden** [comment]
I am inclined to say that this is way over complicated...

**Comment by kameyer226** [comment]
Live tables are painful to deal with but it makes more sense to work with their populated outputs than to fill a separate list from scratch.  Unfortunately the columns for busy and offline have to be converted to string and it was done in a separate loop.

This allows for a script to check if all the appropriate daemons we want working are in fact working prior to launching other scripts and/or bluesky-cmds.    Here we can specialize which ones need to work, since some of them don't really have to be online for many reasons (repair, disconnected, forced deactivation, etc).

**Comment by ksunden** [comment]
And live tables have no place being generated when used as a python library, which is _why_ we have been hesitant to suggest usage of yaqd-control as a library other than in very particular circumstances.

**Comment by kameyer226** [comment]
Please suggest alternative that is not as complex

**Review by ksunden — COMMENTED** [review]
I think it is out of scope to get status as a python library

**Comment by kameyer226** [comment]
Suggest alternative, please, thank you

**Comment by ksunden** [comment]
The alternative is to not do it because it is out of scope for this package.

**Pull request closed without merging**
